"""005_review_fields

Revision ID: 990ac88e827e
Revises: f801bfadde74
Create Date: 2026-05-25 02:32:18.795300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990ac88e827e'
down_revision: Union[str, None] = 'f801bfadde74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('notices', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('talk_records', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('talk_records', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk_records', 'reviewed_at')
    op.drop_column('talk_records', 'review_comment')
    op.drop_column('notices', 'reviewed_at')
    op.drop_column('notices', 'review_comment')
    # ### end Alembic commands ###
